"""Create Post

Revision ID: 1a1561b29cb3
Revises: 
Create Date: 2018-08-02 14:05:08.174163

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1a1561b29cb3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postname',
    sa.Column('imgid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('imgurl', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_info.id'], ),
    sa.PrimaryKeyConstraint('imgid')
    )
    op.drop_index('id_card', table_name='User_Ditiails')
    op.drop_table('User_Ditiails')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User_Ditiails',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('id_card', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('lastlog', mysql.DATETIME(), nullable=True),
    sa.Column('login_num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_info.id'], name='User_Ditiails_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('id_card', 'User_Ditiails', ['id_card'], unique=True)
    op.drop_table('postname')
    # ### end Alembic commands ###
