"""add thumbs1

Revision ID: 1ed24741f040
Revises: ebbebd1f635c
Create Date: 2018-08-06 16:01:56.595077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ed24741f040'
down_revision = 'ebbebd1f635c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('postname', sa.Column('thumbsurl', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('postname', 'thumbsurl')
    # ### end Alembic commands ###
